spring:
  autoconfigure:
    exclude: org.springframework.boot.grpc.server.autoconfigure.security.GrpcServerOAuth2ResourceServerAutoConfiguration
  grpc:
    client:
      channel:
        organization:
          target: ${ORGANIZATION_GRPC_TARGET:organization-service:9090}
          ssl:
            bundle: service
        employee:
          target: ${EMPLOYEE_GRPC_TARGET:employee-service:9090}
          ssl:
            bundle: service
    server:
      port: 9090
      reflection:
        enabled: false
      ssl:
        bundle: service
        client-auth: require
  ssl:
    bundle:
      pem:
        service:
          keystore:
            certificate: ${TLS_CERT}
            private-key: ${TLS_KEY}
          truststore:
            certificate: ${TLS_CA}
