spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ems_notification_db}
    username: ${DB_USERNAME:notification_user}
    password: ${DB_PASSWORD:notification_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
