FROM public.ecr.aws/docker/library/eclipse-temurin:17-jre-jammy
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates && rm -rf /var/lib/apt/lists/* && groupadd --system spring && useradd --system --gid spring spring
WORKDIR /app
COPY --chown=spring:spring app.jar app.jar
USER spring
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
