import { test, expect, type APIRequestContext, type Page } from '@playwright/test';
import { addDays, businessDate, midnight } from '../src/api/attendance';
const password='IntegrationTest123!';
async function token(request:APIRequestContext,email:string){const csrf=await(await request.get('/api/v1/auth/csrf')).json();const r=await request.post('/api/v1/auth/login',{headers:{[csrf.headerName]:csrf.token},data:{email,password}});expect(r.ok(),await r.text()).toBeTruthy();return (await r.json()).accessToken as string;}
async function login(page:Page,email:string){await page.context().clearCookies();await page.goto('/login');await page.getByLabel(/^Email(?:\s*\*)?$/).fill(email);await page.getByLabel(/^Password(?:\s*\*)?$/).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('link',{name:'Schedule',exact:true})).toBeVisible();}
test('published shifts, employee response, PTO conflicts, approval and reversal across real services',async({page,request})=>{
 test.setTimeout(180_000);const suffix=Date.now();const admin=await token(request,'admin@integration.test');const auth=(t:string)=>({Authorization:`Bearer ${t}`});
 async function create(path:string,data:unknown,t=admin){const r=await request.post(path,{headers:auth(t),data});expect(r.ok(),await r.text()).toBeTruthy();return r.json();}
 const location=await create('/api/locations',{name:`Workflow office ${suffix}`});const dept=await create('/api/departments',{name:`Workflow team ${suffix}`,locationId:location.id});const other=await create('/api/departments',{name:`Other workflow ${suffix}`,locationId:location.id});
 async function worker(role:string,departmentId:number,label:string){const email=`${label}-${suffix}@integration.test`;const account=await create('/api/v1/admin/accounts',{email,password,role});const employee=await create('/api/employees',{firstName:label,lastName:'Workflow',email,hireDate:'2026-01-01',departmentId,role,userAccountId:account.id,payRate:'20.00'});return {email,employee,token:await token(request,email)};}
 const employee=await worker('EMPLOYEE',dept.id,'ScheduleWorker');const supervisor=await worker('SUPERVISOR',dept.id,'ScheduleSupervisor');const outsider=await worker('SUPERVISOR',other.id,'OutsideSupervisor');
 const category=await create('/api/shift-categories',{name:`Day ${suffix}`,color:'#abcdef',defaultStartTime:'09:00',defaultEndTime:'17:00'});
 const type=await create('/api/pto/types',{name:`Vacation ${suffix}`,paid:true,accrualRatePerPeriod:0,maxCarryover:0});
 const key=crypto.randomUUID();await create('/api/pto/balances/adjust',{requestKey:key,employeeId:employee.employee.id,ptoTypeId:type.id,hoursDelta:16,reason:'Opening allocation'});await create('/api/pto/balances/adjust',{requestKey:key,employeeId:employee.employee.id,ptoTypeId:type.id,hoursDelta:16,reason:'Opening allocation'});
 const day=addDays(businessDate(),3),start=new Date(Date.parse(midnight(day))+9*3600000).toISOString(),end=new Date(Date.parse(start)+8*3600000).toISOString();
 let shift=await create('/api/shifts',{categoryId:category.id,departmentId:dept.id,locationId:location.id,startsAt:start,endsAt:end,requiredEmployees:1},supervisor.token);
 expect((await request.get(`/api/shifts/${shift.id}`,{headers:auth(outsider.token)})).status()).toBe(403);
 expect((await request.get(`http://localhost:18083/api/shifts/${shift.id}`,{headers:auth(outsider.token)})).status()).toBe(403);
 expect((await request.get('/api/pto/requests',{headers:{'X-User-Id':String(employee.employee.id)}})).status()).toBe(401);
 shift=await create(`/api/shifts/${shift.id}/assign`,{employeeId:employee.employee.id,version:shift.version},supervisor.token);shift=await create(`/api/shifts/${shift.id}/publish`,{version:shift.version},supervisor.token);
 await login(page,employee.email);await expect(page.getByRole('heading',{name:'My work',exact:true})).toBeVisible();await page.getByRole('link',{name:'Schedule',exact:true}).click();await page.getByRole('button',{name:'Accept',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByText('ScheduleWorker Workflow: ACCEPTED',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Time off',exact:true}).click();await page.getByRole('button',{name:'Request time off',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel(/^Leave type/).click();await page.getByRole('option',{name:type.name,exact:true}).click();await dialog.getByLabel(/^Start date/).fill(day);await dialog.getByLabel(/^End date/).fill(day);await dialog.getByLabel(/^Hours/).fill('8');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).not.toBeVisible();
 const rows=await(await request.get('/api/pto/requests/me',{headers:auth(employee.token)})).json();let leave=rows[0];expect(leave.status).toBe('PENDING');
 expect((await request.get(`/api/pto/requests/${leave.id}`,{headers:auth(outsider.token)})).status()).toBe(403);
 expect((await request.get(`http://localhost:18086/api/pto/requests/${leave.id}`,{headers:auth(outsider.token)})).status()).toBe(403);
 const blocked=await request.post(`/api/pto/requests/${leave.id}/decision`,{headers:auth(supervisor.token),data:{version:leave.version,decision:'APPROVED'}});expect(blocked.status()).toBe(409);expect((await blocked.json()).message).toContain(String(shift.id));
 const conflicts=await(await request.get(`/api/pto/requests/${leave.id}/conflicts`,{headers:auth(supervisor.token)})).json();expect(conflicts.shiftIds).toContain(shift.id);
 shift=await(await request.get(`/api/shifts/${shift.id}`,{headers:auth(supervisor.token)})).json();await create(`/api/shift-assignments/${shift.assignments[0].id}/cancel`,{version:shift.assignments[0].version},supervisor.token);
 await login(page,supervisor.email);await page.getByRole('link',{name:'Time off',exact:true}).click();await page.getByRole('button',{name:'Approve',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await expect(page.getByText('APPROVED',{exact:true})).toBeVisible();
 leave=await(await request.get(`/api/pto/requests/${leave.id}`,{headers:auth(employee.token)})).json();expect(leave.status).toBe('APPROVED');const balance=await(await request.get('/api/pto/balances/me',{headers:auth(employee.token)})).json();expect(Number(balance[0].availableHours)).toBe(8);expect(Number(balance[0].usedHours)).toBe(8);
 shift=await(await request.get(`/api/shifts/${shift.id}`,{headers:auth(supervisor.token)})).json();expect((await request.post(`/api/shifts/${shift.id}/assign`,{headers:auth(supervisor.token),data:{employeeId:employee.employee.id,version:shift.version}})).status()).toBe(409);
 leave=await create(`/api/pto/requests/${leave.id}/cancel`,{version:leave.version,reason:'Plans changed'},employee.token);expect(leave.status).toBe('CANCELLED');const restored=await(await request.get('/api/pto/balances/me',{headers:auth(employee.token)})).json();expect(Number(restored[0].availableHours)).toBe(16);
 await create(`/api/shifts/${shift.id}/assign`,{employeeId:employee.employee.id,version:shift.version},supervisor.token);
 const ledger=await(await request.get(`/api/pto/ledger/${employee.employee.id}`,{headers:auth(employee.token)})).json();expect(ledger.map((e:{entryType:string})=>e.entryType).sort()).toEqual(['ADJUSTMENT','REVERSAL','USAGE']);
});
